In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import os, sys
os.chdir("..")
from Source.Models.autoregNN import AutoRegNN
from Source.Networks.energynet import EnergyNet

/usr/local/lib/python3.10/dist-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
params = {"enet_layers":2, "enet_dim":5, "enet_bias":True}
enet = EnergyNet(params)
enet.model_parameters

46

In [11]:
enet(torch.ones(1))

tensor([1.])
tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0.])


tensor([0.])

In [9]:
print(enet.layers[0].weight.size())
print(enet.layers[2].weight.size())
print(enet.layers[4].weight.size())
print(enet.layers[0].bias.size())
print(enet.layers[2].bias.size())
print(enet.layers[4].bias.size())

torch.Size([5, 1])
torch.Size([5, 5])
torch.Size([1, 5])
torch.Size([5])
torch.Size([5])
torch.Size([1])


In [10]:
enet.setWeights(torch.zeros(enet.model_parameters))